language: cpp
sudo: required
dist: bionic
compiler:
  - clang
os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install libgoogle-glog-dev
#  - ./scripts/travis/before_install.sh
script:
  - bash ./scripts/travis/build.sh
  - bash ./scripts/travis/test.sh
