language: cpp
sudo: required
dist: bionic
compiler:
  - clang
os:
  - linux

addons:
  apt:
    packages: lcov

install:
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

before_install:
  - ./scripts/travis/before_install.sh

script:
  - ./scripts/travis/build.sh
  - ./scripts/travis/test.sh

after_success: 
  - ./scripts/travis/get_code_cov.sh
  - bash <(curl -s https://codecov.io/bash) -f coverage.info

notifications:
  email:
    - guozhibin2014@163.com
