language: cpp
sudo: required
dist: bionic
compiler:
  - clang
os:
  - linux

before_install:
  - ./scripts/travis/before_install.sh

script:
  - ./scripts/travis/build.sh
  - ./scripts/travis/test.sh

after_success: 
  - ./scripts/travis/get_code_cov.sh
  - bash <(curl -s https://codecov.io/bash)
